<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEWEM0IO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEWEM0IO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEWEM0IO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEWEM0IO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEWEM0IO\App_KernelDevDebugContainer([
    'container.build_hash' => 'EWEM0IO',
    'container.build_id' => '5c49b2c2',
    'container.build_time' => 1623450059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEWEM0IO');
